apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: platform
spec:
  replicas: {{ .Values.clickhouse.replicas }}
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: {{ .Values.clickhouse.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 8123
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          emptyDir: {}
