apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: platform
spec:
  selector:
    app: clickhouse
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http-interface
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
