apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-k8s-infra-otel-agent
  namespace: platform
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      clickhousemetricswrite:
        endpoint: "clickhouse:9000"
      clickhousetraces:
        endpoint: "clickhouse:9000"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhousemetricswrite]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhousetraces]
