apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: platform
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:22.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000   # TCP port for client connections
            - containerPort: 8123   # HTTP interface
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: platform
spec:
  selector:
    app: clickhouse
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http-interface
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
