apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-k8s-infra-otel-agent
  namespace: platform
  labels:
    app.kubernetes.io/name: k8s-infra
    app.kubernetes.io/component: otel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-infra
      app.kubernetes.io/component: otel-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-infra
        app.kubernetes.io/component: otel-agent
    spec:
      hostNetwork: true
      serviceAccountName: infra-k8s-infra-otel-agent
      containers:
        - name: infra-k8s-infra-otel-agent
          image: docker.io/otel/opentelemetry-collector-contrib:0.109.0
          imagePullPolicy: IfNotPresent
          command: ["/otelcol-contrib"]
          args: ["--config=/conf/otel-agent-config.yaml"]
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz:4318"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /conf
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: config-volume
          configMap:
            name: infra-k8s-infra-otel-agent
