---
apiVersion: v1
kind: Namespace
metadata:
  name: platform

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: platform
spec:
  selector:
    app: clickhouse
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http-interface
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:22.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 8123
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-k8s-infra-otel-agent
  namespace: platform
data:
  otel-collector-config.yaml: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          memory:
          filesystem:
          network:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      clickhousetraces:
        endpoint: "clickhouse.platform.svc.cluster.local:9000"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhousetraces]
        metrics:
          receivers: [hostmetrics]
          processors: [batch]
          exporters: []

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-k8s-infra-otel-agent
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-infra
      app.kubernetes.io/component: otel-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-infra
        app.kubernetes.io/component: otel-agent
    spec:
      containers:
        - name: infra-k8s-infra-otel-agent
          image: signoz/signoz-otel-collector:0.111.25
          imagePullPolicy: IfNotPresent
          env:
            - name: CLICKHOUSE_HOST
              value: "clickhouse.platform.svc.cluster.local"
            - name: CLICKHOUSE_PORT
              value: "9000"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: infra-k8s-infra-otel-agent
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml
